[#31214] YSQL: Tighten partition key checks for single shard updates
Summary:
=== Problem ===

Consider a partitioned table where the root has no primary key, and the leaf declares a primary key that differs from the partition key:

```sql
CREATE TABLE root (cluster_key INT, part_key INT, v INT) PARTITION BY RANGE (part_key);
CREATE TABLE leaf1 PARTITION OF root (cluster_key PRIMARY KEY) FOR VALUES FROM (1) TO (11);
CREATE TABLE leaf2 PARTITION OF root (cluster_key PRIMARY KEY) FOR VALUES FROM (11) TO (21);

INSERT INTO leaf1 VALUES (1, 1, 5);
```

The queries below error out as follows:
```sql
-- Attempt to update the row without specifying the partition key; should succeed
yugabyte=# EXPLAIN (COSTS OFF) UPDATE leaf1 SET v = v + 1 WHERE cluster_key = 1;
     QUERY PLAN
--------------------
 Update on leaf1
   ->  Result leaf1    <--- Single shard transaction
(2 rows)

yugabyte=# UPDATE leaf1 SET v = v + 1 WHERE cluster_key = 1;
ERROR:  23514: new row for relation "leaf1" violates partition constraint
DETAIL:  Failing row contains (1, null, 0).

-- Attempt to move the row from leaf1 to leaf2; should be executed as a distributed transaction and should fail the partition constraint check
yugabyte=# EXPLAIN UPDATE leaf1 SET v = v + 1, part_key = 15 WHERE cluster_key = 1;
     QUERY PLAN
--------------------
 Update on leaf1
   ->  Result leaf1      <--- Single shard transaction
(2 rows)

yugabyte=# UPDATE leaf1 SET v = v + 1, part_key = 15 WHERE cluster_key = 1;
ERROR:  23514: new row for relation "leaf1" violates partition constraint
DETAIL:  Failing row contains (1, 15, 0).
```

Both of these queries are planned as single-shard updates. Their planning/execution highlights two distinct problems:
 - When the partition key is not provided in the UPDATE statement (neither in the WHERE clause nor in the SET clause) there is not enough information available at execution time to perform the partition constraint check for the row to be updated.
 -  When the partition key is distinct from the clustering key and is modified by the UPDATE (specified in the SET clause), single-shard updates should be disallowed for the statement to prevent a row from being silently moved to an incorrect partition. However, the current code in the planner incorrectly allows such updates. Further downstream in the execution layer, the partition check fails, preventing the cross partition update from being executed as a single shard transaction.

Phrased another way, leaf partitions involve two levels of placement decisions: the clustering (primary) key determines which tablet a row lives in, while the partition key determines which table partition (and therefore tablet) a row is routed to. Therefore any update that modifies either key must be disallowed for single-shard updates. Consequently, with both of these modifications blocked, re-checking the partition constraint is redundant.

=== Fix ===
The revision applies two fixes:
 - The function `yb_single_row_update_or_delete_path()` in the planner determines if the given UPDATE is eligible for a single-shard transaction. This function is augmented to check for modifications in the partition key while making its decision. Single-shard updates that reach the executor are guaranteed not to change which tablet a row belongs to.
 - As a result, the executor-level partition constraint check is now skipped if the row is updated as part of a single-shard transaction.

Examining the partition key involves a few considerations:
 - Partition information (what columns and expressions form the partition key) is present in the parent partition's `pg_partitioned_table` entry, and not the child's.
 - The parent partition may have columns in a different order when compared to the child partion (ex. [a, b, c] in the parent vs [c, b, a] in the child). Therefore, the list of updated columns in the child have to be mapped to the parent's column space.
 - The child partition could be a part of a multi-level partitioning hierarchy. For example, the `grandparent` could be partitioned on a key k1, while the `parent` could be partitioned on a key k2. A child of `parent` is explicitly partitioned via key k2, but is also implicitly partitioned via key k1. Therefore, the partition key examination must examine all ancestors in the hierarchy.
 - Postgres does not provide convenient APIs to selectively map a set of columns from the child's column space to the parent's. The execution layer does the reverse: it exposes an API to construct a map from the parent's column space to the child's. This map contains all of the columns. This revision reuses this API.

Test Plan:
Run the following test:
```
./yb_build.sh --java-test 'org.yb.pgsql.TestPgRegressDml#schedule'
```

Reviewers: fizaa, aagrawal, jason

Reviewed By: fizaa

Subscribers: jason, yql, smishra

Tags: #jenkins-ready

Differential Revision: https://phorge.dev.yugabyte.com/D52579