[#30786] YSQL: Fix failing test TestDdlTransactionBlocks
Summary:
Test TestDdlTransactionBlocks fails with the following diff

```
diff -U3 ${TEST_TMPDIR}/pgregress_output/yb_ddl_txn_block_schedule/expected/yb.orig.ddl_txn_block.out ${TEST_TMPDIR}/pgregress_output/yb_ddl_txn_block_schedule/results/yb.orig.ddl_txn_block
.out
--- ${TEST_TMPDIR}/pgregress_output/yb_ddl_txn_block_schedule/expected/yb.orig.ddl_txn_block.out        2026-05-13 13:13:52.867153620 +0000
+++ ${TEST_TMPDIR}/pgregress_output/yb_ddl_txn_block_schedule/results/yb.orig.ddl_txn_block.out 2026-05-13 13:13:52.807154701 +0000
@@ -528,23 +528,22 @@
 ERROR:  integer out of range
 -- Test rollback of in-place index pg_attribute update during ALTER TYPE.
 CREATE TABLE test_idx_rollback (val varchar(10));
+ERROR:  current transaction is aborted, commands ignored until end of transaction block
 CREATE INDEX idx_rollback ON test_idx_rollback(val);
+ERROR:  current transaction is aborted, commands ignored until end of transaction block
 ALTER TABLE test_idx_rollback ALTER COLUMN val TYPE varchar(100);
+ERROR:  current transaction is aborted, commands ignored until end of transaction block
 SELECT atttypmod FROM pg_attribute
     WHERE attrelid = 'idx_rollback'::regclass AND attnum = 1;
- atttypmod
------------
-       104
-(1 row)
-
+ERROR:  current transaction is aborted, commands ignored until end of transaction block
 BEGIN;
+ERROR:  current transaction is aborted, commands ignored until end of transaction block
 ALTER TABLE test_idx_rollback ALTER COLUMN val TYPE varchar(200);
+ERROR:  current transaction is aborted, commands ignored until end of transaction block
 ROLLBACK;
 -- atttypmod should revert to 104 (varchar(100)) after rollback.
 SELECT atttypmod FROM pg_attribute
     WHERE attrelid = 'idx_rollback'::regclass AND attnum = 1;
- atttypmod
------------
-       104
-(1 row)
-
+ERROR:  relation "idx_rollback" does not exist
+LINE 2:     WHERE attrelid = 'idx_rollback'::regclass AND attnum = 1...
+                             ^
```

The issue is introduced by 2ab776e1bca8 / D52287 because it removes the reconnect command \c. The reconnect command aborts the ongoing transaction and hence removing it also removes the txn release. As a consequence of removing the reconnect command, subsequent commands in the test file yb.orig.ddl_txn_block.sql started failing since the transaction wasnt closed.

To fix this, add an explicit ROLLBACK command. That closes out the txn and no longer raises error `current transaction is aborted, commands ignored until end of transaction block`

Test Plan:
Jenkins

./yb_build.sh release --java-test TestDdlTransactionBlocks

Backport-through: 2025.2

Reviewers: pjain, myang, smishra

Reviewed By: myang

Subscribers: jason, yql

Differential Revision: https://phorge.dev.yugabyte.com/D53140